### ISSUE TITLE
Reset Password Not Working 

### ISSUE THREAD

**Issue by mbyrdLCS** [LiveChurchSolutions/LessonsApp#74]
When you click forgot password the email leads you back to a login on churchapps it does not give you the option to reset your password

**Comment by pranavmalvawala** [comment]
It should work now.
 
After clicking on the reset password link - the user will be redirected to churchApps, from there after selecting a church from the modal will lead them to profile page where they can update the password. Let me know how it goes or in case you expect a different flow.

**Comment by mbyrdLCS** [comment]
This is the link I get it is not leading me to anywhere to reset the password 
Please click here to reset your password: https://accounts.staging.churchapps.org/login?auth=4b796d1d-cb45-4583-bc09-31f3f3c63003"

**Comment by pranavmalvawala** [comment]
Oh, the link is supposed to just work once. If you've already used this once, it won't work next time. I think adding this information to mail should resolve this confusion, user's won't take the reset links for granted. 

You should give it a try again. I've fixed it. It should take you directly to profile page ( where we can change password ) after church selection.

**Comment by mbyrdLCS** [comment]
This is still not working I understand the link can only used once but it does not work there is no way to change the password.

**Comment by jzongker** [comment]
I've added a profile link to the user drop down menu to enable you to change your password once the one-time code gets you logged back in.

It's on staging now, and will be deployed to prod later today.
